version: '3'
services:
  mysql:
   image: mysql:5.7.8
   ports:
    - "3306:3306"
   networks:
    - demodocker
#   network_mode: host
   environment:
    - MYSQL_ROOT_PASSWORD=milkmachine
    - MYSQL_DATABASE=animal
   volumes:
    - "./conf.d:/etc/mysql/conf.d:rw"
    - "./conf.d/data:/var/lib/mysql"
  spring:
    image: narendrajava1/demodocker:1.0
    ports:
     - "9696:9696"
    networks:
     - demodocker
#    network_mode: host
    depends_on:
     - mysql
#networks:
#petclinic: